/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelectSectionsRouteImport } from './routes/select/sections'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectSectionsRoute = SelectSectionsRouteImport.update({
  id: '/select/sections',
  path: '/select/sections',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/timetable': typeof TimetableRoute
  '/select/sections': typeof SelectSectionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/timetable': typeof TimetableRoute
  '/select/sections': typeof SelectSectionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/timetable': typeof TimetableRoute
  '/select/sections': typeof SelectSectionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/timetable' | '/select/sections'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/timetable' | '/select/sections'
  id: '__root__' | '/' | '/timetable' | '/select/sections'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimetableRoute: typeof TimetableRoute
  SelectSectionsRoute: typeof SelectSectionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select/sections': {
      id: '/select/sections'
      path: '/select/sections'
      fullPath: '/select/sections'
      preLoaderRoute: typeof SelectSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimetableRoute: TimetableRoute,
  SelectSectionsRoute: SelectSectionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
