"""drop_otp_verifications_table

Revision ID: 9df6712fcb2b
Revises: b0156d8b7801
Create Date: 2026-07-19 17:05:27.928048

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9df6712fcb2b"
down_revision: str | Sequence[str] | None = "b0156d8b7801"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_kiittime_otp_verifications_roll_no"),
        table_name="otp_verifications",
        schema="kiittime",
    )
    op.drop_table("otp_verifications", schema="kiittime")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otp_verifications",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("roll_no", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("otp_code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "section_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("otp_verifications_pkey")),
        schema="kiittime",
    )
    op.create_index(
        op.f("ix_kiittime_otp_verifications_roll_no"),
        "otp_verifications",
        ["roll_no"],
        unique=False,
        schema="kiittime",
    )
    # ### end Alembic commands ###
