"""update_roll_number_mapping_unique_constraint

Revision ID: db31445784ed
Revises: a9c44024aff2
Create Date: 2026-07-20 14:26:05.652295

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db31445784ed"
down_revision: str | Sequence[str] | None = "a9c44024aff2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("roll_number_mappings_roll_no_section_id_key"),
        "roll_number_mappings",
        schema="kiittime",
        type_="unique",
    )
    op.create_unique_constraint(
        None, "roll_number_mappings", ["roll_no", "section_id", "academic_year"], schema="kiittime"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "roll_number_mappings", schema="kiittime", type_="unique")
    op.create_unique_constraint(
        op.f("roll_number_mappings_roll_no_section_id_key"),
        "roll_number_mappings",
        ["roll_no", "section_id"],
        schema="kiittime",
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
