"""add_roll_number_mappings

Revision ID: 53af5650caec
Revises: 47595667330f
Create Date: 2026-07-19 11:30:41.554924

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53af5650caec"
down_revision: str | Sequence[str] | None = "47595667330f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roll_number_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("roll_no", sa.String(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("academic_year", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["kiittime.sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("roll_no", "section_id"),
        schema="kiittime",
    )
    op.create_index(
        op.f("ix_kiittime_roll_number_mappings_roll_no"),
        "roll_number_mappings",
        ["roll_no"],
        unique=False,
        schema="kiittime",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_kiittime_roll_number_mappings_roll_no"),
        table_name="roll_number_mappings",
        schema="kiittime",
    )
    op.drop_table("roll_number_mappings", schema="kiittime")
    # ### end Alembic commands ###
