"""create initial schema

Revision ID: 53f4fae4babb
Revises:
Create Date: 2026-07-12 17:54:32.491787

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53f4fae4babb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS kiittime")
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_code", sa.String(), nullable=False),
        sa.Column("course_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_code"),
        schema="kiittime",
    )
    op.create_table(
        "faculty",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("faculty_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("faculty_name"),
        schema="kiittime",
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_number", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_number"),
        schema="kiittime",
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section_name", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section_name", "year"),
        schema="kiittime",
    )
    op.create_table(
        "class_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("faculty_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.String(), nullable=False),
        sa.Column("period_number", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["kiittime.courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["kiittime.faculty.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["kiittime.rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["kiittime.sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section_id", "day", "period_number"),
        schema="kiittime",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("class_sessions", schema="kiittime")
    op.drop_table("sections", schema="kiittime")
    op.drop_table("rooms", schema="kiittime")
    op.drop_table("faculty", schema="kiittime")
    op.drop_table("courses", schema="kiittime")
    op.execute("DROP SCHEMA IF EXISTS kiittime")
    # ### end Alembic commands ###
