"""Make faculty_id nullable

Revision ID: a9c44024aff2
Revises: 9df6712fcb2b
Create Date: 2026-07-20 13:08:29.721726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c44024aff2'
down_revision: Union[str, Sequence[str], None] = '9df6712fcb2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_sessions', 'faculty_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='kiittime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_sessions', 'faculty_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='kiittime')
    # ### end Alembic commands ###
