"""add_otp_verifications_table

Revision ID: b0156d8b7801
Revises: 53af5650caec
Create Date: 2026-07-19 13:49:38.127935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0156d8b7801'
down_revision: Union[str, Sequence[str], None] = '53af5650caec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('section_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='kiittime'
    )
    op.create_index(op.f('ix_kiittime_otp_verifications_roll_no'), 'otp_verifications', ['roll_no'], unique=False, schema='kiittime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiittime_otp_verifications_roll_no'), table_name='otp_verifications', schema='kiittime')
    op.drop_table('otp_verifications', schema='kiittime')
    # ### end Alembic commands ###
