"""add admin_users table

Revision ID: f032a37a4315
Revises: 0dabea0c5b70
Create Date: 2026-07-14 10:42:41.191893

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f032a37a4315"
down_revision: str | Sequence[str] | None = "0dabea0c5b70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="kiittime",
    )
    op.create_index(
        op.f("ix_kiittime_admin_users_username"),
        "admin_users",
        ["username"],
        unique=True,
        schema="kiittime",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_kiittime_admin_users_username"), table_name="admin_users", schema="kiittime"
    )
    op.drop_table("admin_users", schema="kiittime")
    # ### end Alembic commands ###
